#!/bin/bash

# Aggregate Daily Logs Script
# Pulls today's logs from all worktrees and creates unified dashboard

set -e

CALEN_DIR="${HOME}/projects/Calen"
WORKTREES_DIR="${CALEN_DIR}/worktrees"
TODAY=$(date +%Y-%m-%d)
DAY_NAME=$(date +%A)
OUTPUT_FILE="${CALEN_DIR}/dashboard-${TODAY}.md"

echo "# Daily Dashboard - ${TODAY} (${DAY_NAME})" > "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"
echo "Generated at $(date '+%H:%M:%S')" >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"
echo "---" >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"

# List of all worktrees
PROJECTS=(
    "vlaid:Vlaid"
    "willow-co:Willow & Co"
    "network:Network"
    "verzi:Verzi LLC"
    "diathrive:Diathrive"
    "maturi:Maturi BR"
    "graphene:Graphene"
    "cms-star-ratings:CMS Star Ratings"
    "sportsmarkets:SportsMarkets"
    "execwatchdog:ExecWatchDog"
    "retrocashrush:Retro Cash Rush"
    "momentbeheld:MomentBeheld"
    "personal:Personal"
)

for PROJECT_ENTRY in "${PROJECTS[@]}"; do
    WORKTREE=$(echo "${PROJECT_ENTRY}" | cut -d: -f1)
    PROJECT_NAME=$(echo "${PROJECT_ENTRY}" | cut -d: -f2)
    LOG_FILE="${WORKTREES_DIR}/${WORKTREE}/daily-log.md"

    if [ -f "${LOG_FILE}" ]; then
        echo "## ${PROJECT_NAME}" >> "${OUTPUT_FILE}"
        echo "" >> "${OUTPUT_FILE}"

        # Check if today's entry exists
        if grep -q "## ${TODAY}" "${LOG_FILE}" 2>/dev/null; then
            # Extract today's section
            sed -n "/## ${TODAY}/,/^## [0-9]/p" "${LOG_FILE}" | head -n -1 >> "${OUTPUT_FILE}"
        else
            echo "_No entries for today_" >> "${OUTPUT_FILE}"
        fi

        echo "" >> "${OUTPUT_FILE}"
        echo "---" >> "${OUTPUT_FILE}"
        echo "" >> "${OUTPUT_FILE}"
    fi
done

echo "" >> "${OUTPUT_FILE}"
echo "---" >> "${OUTPUT_FILE}"
echo "_Dashboard generated by Calen Chief of Staff System_" >> "${OUTPUT_FILE}"

echo "Dashboard created: ${OUTPUT_FILE}"
